### ISSUE TITLE
UnUnit() of AUI should not be in __del__ of the MainFrame (Python code generation)

### ISSUE THREAD

**Issue by dhyams** [wxFormBuilder/wxFormBuilder#623]
self.m_mgr.UnInit() should be moved to the OnClose event handler, rather than being in the __del__ magic method for the frame.  An app using AUI will get this message:

Traceback (most recent call last):
  File "spallgui.py", line 175, in <module>
    app.MainLoop()
  File "C:\venvs\spall\lib\site-packages\wx\core.py", line 2224, in MainLoop
    rv = wx.PyApp.MainLoop(self)
wx._core.wxAssertionError: C++ assertion "GetEventHandler() == this" failed at ..\..\src\common\wincmn.cpp(475) in wxWindowBase::~wxWindowBase(): any pushed event handlers must have been removed
This is further discussed here; I ran into exactly the same problem:
https://discuss.wxpython.org/t/aui-error-any-pushed-event-handlers-must-have-been-removed/34555

**Comment by sodevel** [comment]
I don't know any Python, in C++ it is sufficient to uninitialize in the destructor because of destructor chaining this call will be executed before the base class destructor that performs this check. Are you sure the problem is that this call doesn't get executed? Or did your user code push an own handler and you forgot to remove it so that the automatic removal sees the wrong event handler?

Putting that cleanup code into the close event handler does not work because it interferes with user code. If the user doesn't define that handler it doesn't exist. If the generator defines one and the user code as well, how can you ensure the generator one does get executed in the correct order (after the user code one)?

I somehow doubt that in Python no chaining of destructors is performed, how does proper cleanup of objects with inheritance work there? Or is it a wxPython problem that works differently than in C++ and you have to cleanup AUI in another way?

**Comment by dhyams** [comment]
The issue (as I grok it from the wxpython discussion thread linked in the OP) is that the UnUnit comes too late; that by the time __del__ is called, the GUI has been destroyed.  I defer to Robin Dunn on this one (author of wxPython), but this is basically what he says in the discussion thread.  And it does work to move the UnInit() to Close().

I fully sympathize with your second paragraph.  Bottom line is that yes, you can define work to do in OnClose(), but it will still be up to the user's override of OnClose (if they have one) to call it.

I *think*, but I'm not sure, that yes, cleaning up AUI has to work differently in Python than in C++.

**Comment by Kvaz1r** [comment]
I hope that PR [Call wxAuiManager::UnInit() automatically](https://github.com/wxWidgets/wxWidgets/pull/1982) will be merged for new release so in new code one won't need call UnInit every time at all. As far I understand wxPython is very active binding so those change will be apply soon if they appear in wxWidgets repo.

**Comment by dhyams** [comment]
@Kvaz1r I see that 12 days ago, the PR you reference was merged.

**Comment by Kvaz1r** [comment]
In that case - just wait while 3.1.4 will be ported to wxPython.
