### ISSUE TITLE
Always crash when trying to generate XRC for a form contains collapsiblepanel

### ISSUE THREAD

**Issue by stirwl** [wxFormBuilder/wxFormBuilder#703]
[CrashOnGenXRCForCollapsiblepanel.fbp.zip](https://github.com/wxFormBuilder/wxFormBuilder/files/7316658/CrashOnGenXRCForCollapsiblepanel.fbp.zip
![CrashOnGenXRCForCollapsiblepanel](https://user-images.githubusercontent.com/19604610/136677713-e8086837-9c22-45ef-bc29-1031359bb3ea.PNG)
)

**Comment by stirwl** [comment]
I think I find the reason.
It is because the wxCollapsiblePane has no child. (I didn't add child for them yet.)
So that the children size is 0.
The assert will fire when get child idx=0.


PObjectBase ObjectBase::GetChild (unsigned int idx)
{
	assert (idx < m_children.size());

	return m_children[idx];
}

#7  0x00007ff9d9af8083 in strerror_s () from C:\Windows\system32\msvcrt.dll
#8  0x00007ff9d9af59f9 in msvcrt!_wassert ()
   from C:\Windows\system32\msvcrt.dll
#9  0x00007ff6ea837ebe in ObjectBase::GetChild (this=0xefa5148610, idx=0)
    at C:/msys64/home/long/wxFormBuilder/src/model/objectbase.cpp:490
#10 0x00007ff6ea821fde in XrcCodeGenerator::GetElement (this=0xefa101dd60,
    obj=std::shared_ptr<ObjectBase> (use count 4, weak count 90) = {...},
    parent=0xefa51135e0)
    at C:/msys64/home/long/wxFormBuilder/src/codegen/xrccg.cpp:199
#11 0x00007ff6ea822104 in XrcCodeGenerator::GetElement (this=0xefa101dd60,
    obj=std::shared_ptr<ObjectBase> (use count 2, weak count 5) = {...},
    parent=0xefa5103d90)
    at C:/msys64/home/long/wxFormBuilder/src/codegen/xrccg.cpp:212
#12 0x00007ff6ea822104 in XrcCodeGenerator::GetElement (this=0xefa101dd60,
    obj=std::shared_ptr<ObjectBase> (use count 5, weak count 14) = {...},
    parent=0xefa5109970)
    at C:/msys64/home/long/wxFormBuilder/src/codegen/xrccg.cpp:212
#13 0x00007ff6ea821c9f in XrcCodeGenerator::GetElement (this=0xefa101dd60,
    obj=std::shared_ptr<ObjectBase> (use count 4, weak count 77) = {...},
    parent=0x0) at C:/msys64/home/long/wxFormBuilder/src/codegen/xrccg.cpp:161
#14 0x00007ff6ea82131b in XrcCodeGenerator::GenerateCode (this=0xefa101dd60,
    project=std::shared_ptr<ObjectBase> (use count 7, weak count 29) = {...})
    at C:/msys64/home/long/wxFormBuilder/src/codegen/xrccg.cpp:57
#15 0x00007ff6ea8c7aaf in XrcPanel::OnCodeGeneration (this=0xefa50bf780,
    event=...)
    at C:/msys64/home/long/wxFormBuilder/src/rad/xrcpanel/xrcpanel.cpp:204
