### ISSUE TITLE
Codegen crash when a menu is attached to an AUI toolbar tool

### ISSUE THREAD

**Issue by davidgiven** [wxFormBuilder/wxFormBuilder#757]
This is with 3.10.1.0, the Debian x64 version.

Adding a menu to a tool in a AUI toolbar causes a codegen crash for C++, Python or PHP. XRC is fine, because it's not doing anything, and Lua is fine, because it doesn't try to do codegen for AUI toolbars.

A minimal example is attached --- just load this and go to the C++ codegen tab.

[minimal.zip](https://github.com/wxFormBuilder/wxFormBuilder/files/9485616/minimal.zip)

**Comment by davidgiven** [comment]
Stacktrace:

```
#0  0x000056217a085a75 in TemplateParser::ParseWxParent() ()
#1  0x000056217a0868fa in TemplateParser::ParseTemplate() ()
#2  0x000056217a088803 in TemplateParser::ParseIfParentTypeEqual() ()
#3  0x000056217a086440 in TemplateParser::ParseMacro() ()
#4  0x000056217a0868fa in TemplateParser::ParseTemplate() ()
#5  0x000056217a086cf2 in TemplateParser::ParseIfEqual() ()
#6  0x000056217a086460 in TemplateParser::ParseMacro() ()
#7  0x000056217a0868fa in TemplateParser::ParseTemplate() ()
#8  0x000056217a0884a2 in TemplateParser::ParseIfNotNull() ()
#9  0x000056217a0868fa in TemplateParser::ParseTemplate() ()
#10 0x000056217a095282 in CppCodeGenerator::GenDefinedEventHandlers(std::shared_ptr<ObjectInfo>, std::shared_ptr<ObjectBase>) ()
#11 0x000056217a09588b in CppCodeGenerator::GetGenEventHandlers(std::shared_ptr<ObjectBase>) ()
#12 0x000056217a0957a1 in CppCodeGenerator::GetGenEventHandlers(std::shared_ptr<ObjectBase>) ()
#13 0x000056217a0957a1 in CppCodeGenerator::GetGenEventHandlers(std::shared_ptr<ObjectBase>) ()
#14 0x000056217a0957a1 in CppCodeGenerator::GetGenEventHandlers(std::shared_ptr<ObjectBase>) ()
#15 0x000056217a0957a1 in CppCodeGenerator::GetGenEventHandlers(std::shared_ptr<ObjectBase>) ()
#16 0x000056217a0957a1 in CppCodeGenerator::GetGenEventHandlers(std::shared_ptr<ObjectBase>) ()
#17 0x000056217a0957a1 in CppCodeGenerator::GetGenEventHandlers(std::shared_ptr<ObjectBase>) ()
#18 0x000056217a0957a1 in CppCodeGenerator::GetGenEventHandlers(std::shared_ptr<ObjectBase>) ()
#19 0x000056217a0957a1 in CppCodeGenerator::GetGenEventHandlers(std::shared_ptr<ObjectBase>) ()
#20 0x000056217a0957a1 in CppCodeGenerator::GetGenEventHandlers(std::shared_ptr<ObjectBase>) ()
#21 0x000056217a0957a1 in CppCodeGenerator::GetGenEventHandlers(std::shared_ptr<ObjectBase>) ()
#22 0x000056217a0a907a in CppCodeGenerator::GenClassDeclaration(std::shared_ptr<ObjectBase>, bool, wxString const&, std::vector<std::shared_ptr<Event>, std::allocator<std::shared_ptr<Event> > > const&, std::map<wxString, CodeGenerator::ArrayItem, std::less<wxString>, std::allocator<std::pair<wxString const, CodeGenerator::ArrayItem> > >&) ()
#23 0x000056217a0ab735 in CppCodeGenerator::GenerateCode(std::shared_ptr<ObjectBase>) ()
#24 0x000056217a190665 in CppPanel::OnCodeGeneration(wxFBEvent&) ()
#25 0x00007f896d9dc15e in wxEvtHandler::ProcessEventIfMatchesId(wxEventTableEntryBase const&, wxEvtHandler*, wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#26 0x00007f896d9dc253 in wxEventHashTable::HandleEvent(wxEvent&, wxEvtHandler*) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#27 0x00007f896d9dc58c in wxEvtHandler::TryHereOnly(wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#28 0x00007f896d9dc61b in wxEvtHandler::ProcessEventLocally(wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#29 0x00007f896d9dc6f1 in wxEvtHandler::ProcessEvent(wxEvent&) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#30 0x000056217a142b00 in ApplicationData::NotifyEvent(wxFBEvent&, bool) [clone .constprop.0] ()
#31 0x000056217a14521e in ApplicationData::GenerateCode(bool, bool) ()
#32 0x000056217a07bad2 in MyApp::OnRun() ()
#33 0x00007f896d902a19 in wxEntry(int&, wchar_t**) () at /usr/lib/x86_64-linux-gnu/libwx_baseu-3.0.so.0
#34 0x000056217a072db8 in main ()
